version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h6psdecnr2wt"
s3_prefix = "hello1"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"

