AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  S3Primary:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sashumi-sam-test-241120
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function1/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Function1:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  Function1Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

